
ALTER TABLE threads ADD COLUMN last_indexed_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE blog_posts ADD COLUMN last_indexed_at TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE users ADD COLUMN last_indexed_at TIMESTAMP NULL DEFAULT NULL;
