
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_indexed_at DATETIME NULL;
ALTER TABLE threads ADD COLUMN IF NOT EXISTS last_indexed_at DATETIME NULL;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS last_indexed_at DATETIME NULL;
